PORT:
  default: 7777
  description: The port on which your app runs
NODE_ENV:
  default: false
  description: Set to "development" on local machines
FORCE_SSL:
  default: false
  description: Is this server running behind an SSL-enabled load-balancer? (true | false)
ENABLE_GELF_LOGS:
  default: false
  description: Set to true to enable GELF formatted logging. Set to false to enable express.logger for logging
RESTART:
  default: 1
  description: For running multiple copies of the server. See cluster.js
FORKS:
  default: 2
  description: For running multiple copies fo the server. See cluster.js

#Flags
FLAG_EXPLORE:
  default: false
  description: Displays new explore. DO NOT USE IN PROD. (true | false)
FLAGS_HOUROFCODE:
  default: false
  description: Displays 'hour of code' campaign message (true | false)
FLAGS_CAMPAIGN:
  default: 0
  description: 'If 0, the campaign banner will not show. If a number greater than 0, the campaign banner will choose from a set of variations.'

# i18n Language Support
SUPPORTED_LANGS:
  default: '[ "*" ]'
  description: 'Should be a string containing an array of languages e.g. [ "en", "fr"]'
  required: true

# Badges
BADGES_ENDPOINT:
  default: https://badgekit-api.mofostaging.net
  description: 'Badgekit API endpoint. https://badgekit-api.mofostaging.net for staging, https://api.badgekit.org for prod'
  required: true
BADGES_KEY:
  default: master
  description: Key for badgekit api. "master" for staging
  required: true
BADGES_SECRET:
  description: Secret key for badgekit api. Ping @k88hudson for dev credentials
BADGES_SYSTEM:
  default: webmaker
  description: The badges "system" in badgekit-api. See badgekit-api docs.
  required: true

# MakeAPI
MAKE_ENDPOINT:
  default: http://localhost:5000
  description: The makeapi endpoint for authenticated routes. Staging is http://makeapi.mofostaging.net
  required: true
MAKE_ENDPOINT_READONLY:
  default: https://makeapi.webmaker.org
  description: If you need to see read-only sections of the site (e.g. galleries) with real data use this. Prod is https://makeapi.webmaker.org
  required: true
MAKE_PUBLICKEY:
  default: 00000000-0000-0000-000000000000
  description: Public key for MakeAPI. Must be generated by make-api or if in dev mode should be 00000000-0000-0000-000000000000
MAKE_PRIVATEKEY:
  default: 00000000-0000-0000-000000000000
  description: Private key for MakeAPI. Must be generated by make-api or if in dev mode should be 00000000-0000-0000-000000000000
  required: true

# Login
LOGIN:
  default: http://localhost:3000
  description: Login API endpoint
  required: true
SESSION_SECRET:
  default: dummy secret value
  description: Session secret to decode user sessions
  warning: THIS SHOULD MATCH ALL OTHER WEBMAKER.ORG APPS ESPECIALLY LOGIN.WEBMAKER.ORG
  required: true
COOKIE_DOMAIN:
  description: Use this to support supercookies for webmaker login. Do not use on localhost.
PERSONA_HOSTNAME:
  description: For use with local persona installations. Try http://localhost:10002
PERSONA_VERIFIER_URI:
  description: For use with local persona installations. Try http://localhost:10000/verify

# Google Analytics info
GA_ACCOUNT:
  description: For google analytics
GA_DOMAIN:
  description: For google analytics

# Other services
PROFILE_URL:
  default: 'https://{{username}}.webmakerprofile.com'
  description: 'Format the profile URL like this https://{{username}}.webmakerprofile.com'
EVENTS_URL:
  default: http://localhost:1981
  description: Domain of the webmaker-events front end

